name: akipro_env
channels:
  - defaults
dependencies:
  - python=3.8.12
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.0.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - matplotlib=3.5.0
  - numpy=1.21.2
  - scipy=1.7.1
  - scikit-learn=0.23.2
  - ipykernel=6.4.1
  - pandas=1.1.3
  - pip=21.0.1
  - pywin32=228
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jupyter_client=7.0.1
  - jupyter_core=4.8.1
  - pip:
    - keras-visualizer==2.4
    - graphviz==0.18
    - opencv-python
    - tensorflow==2.4.1
    - keras==2.4.3
    - notebook==6.4.7
    - imgaug
    
